
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Manish Kumar
 */
public class NewBook extends javax.swing.JFrame {

    /**
     * Creates new form NewBook
     */
    public NewBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        f3 = new javax.swing.JTextField();
        f2 = new javax.swing.JTextField();
        f4 = new javax.swing.JTextField();
        f1 = new javax.swing.JTextField();
        f5 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        f3.setBackground(new java.awt.Color(0, 0, 0));
        f3.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        f3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(f3, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 253, 358, 51));

        f2.setBackground(new java.awt.Color(0, 0, 0));
        f2.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        f2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 183, 358, 51));

        f4.setBackground(new java.awt.Color(0, 0, 0));
        f4.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        f4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(f4, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 336, 358, 51));

        f1.setBackground(new java.awt.Color(0, 0, 0));
        f1.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        f1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 100, 358, 51));

        f5.setBackground(new java.awt.Color(0, 0, 0));
        f5.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        f5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(f5, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 416, 358, 51));

        b1.setBackground(new java.awt.Color(0, 51, 255));
        b1.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        b1.setText("SAVE");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 160, 50));

        jLabel1.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Book ID :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 101, 217, 49));

        jLabel2.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 184, 217, 49));

        jLabel3.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Price :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 337, 217, 49));

        jLabel5.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Publisher Year :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 417, 217, 49));

        jLabel4.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Publisher :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 254, 217, 49));

        jLabel6.setFont(new java.awt.Font("David", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("    X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(904, 0, 34, 33));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Manish Kumar\\Downloads\\thought-catalog-o0Qqw21-0NI-unsplash.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 570));

        setBounds(425, 125, 936, 568);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        String bookId = f1.getText();
        String name = f2.getText();
        String publisher = f3.getText();
        String price = f4.getText();
        String publisherYear = f5.getText();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
          Connection Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/lms","root","root");
          Statement St = Con.createStatement();
          System.out.print("done");
          St.executeUpdate("insert into newbook values('"+bookId+"','"+name+"','"+publisher+"','"+price+"','"+publisherYear+"')");
          JOptionPane.showMessageDialog(this,"Successfully Added...");
          setVisible(false);
          new NewBook().setVisible(true);
        }
        catch(Exception e){
                JOptionPane.showMessageDialog(this,"Missing Statement!!!");
          setVisible(false);
          new NewBook().setVisible(true);
                }
        
    }//GEN-LAST:event_b1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JTextField f1;
    private javax.swing.JTextField f2;
    private javax.swing.JTextField f3;
    private javax.swing.JTextField f4;
    private javax.swing.JTextField f5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
