
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Manish Kumar
 */
public class Returnbook extends javax.swing.JFrame {

    /**
     * Creates new form Returnbook
     */
    public Returnbook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        f2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        f1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        f3 = new javax.swing.JTextField();
        f4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        f2.setBackground(new java.awt.Color(0, 0, 0));
        f2.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        f2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 358, 51));

        jLabel1.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Book ID :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 217, 49));

        jLabel2.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 217, 49));

        jLabel3.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Issue Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 217, 49));

        jLabel4.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Due Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 217, 49));

        f1.setBackground(new java.awt.Color(0, 0, 0));
        f1.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        f1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 358, 51));

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 160, 50));

        jLabel6.setFont(new java.awt.Font("David", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("    X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(904, 0, 34, 33));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Manish Kumar\\Downloads\\Icon 1\\search.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 40, 30));

        f3.setBackground(new java.awt.Color(0, 0, 0));
        f3.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        f3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(f3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 358, 51));

        f4.setBackground(new java.awt.Color(0, 0, 0));
        f4.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        f4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(f4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 358, 51));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Manish Kumar\\Downloads\\jamie-taylor--9C3TMXwQjQ-unsplash.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 560));

        setBounds(425, 125, 935, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String bookId = f1.getText();
        String studentId = f2.getText();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
          Connection Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/lms","root","root");
          Statement St = Con.createStatement();
          St.executeUpdate("update issuebook set ReturnBook='Yes' where BookId='"+bookId+"' and studentID='"+studentId+"'");
          JOptionPane.showMessageDialog(this,"Successfully Return!!!!");
          setVisible(false);
          new Returnbook().setVisible(true);
        }
        catch(Exception e){
                JOptionPane.showMessageDialog(this,"Connection Error!!!");
//          setVisible(false);
//          new Returnbook().setVisible(true);
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String bookId = f1.getText();
        String studentId = f2.getText();    
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
          Connection Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/lms","root","root");
          Statement St = Con.createStatement();
           ResultSet rs =St.executeQuery("select * from issuebook where BookId='"+bookId+"' and studentID='"+studentId+"'");
          if(rs.next()){
              f3.setText(rs.getString(3));
              f4.setText(rs.getString(4));
              
              
          }else{
           JOptionPane.showMessageDialog(this,"Book is not Issued to this Student");
          setVisible(false);
          new Returnbook().setVisible(true);
          }
        }
        catch(Exception e){
                JOptionPane.showMessageDialog(this,"Conncation Error!!!");
                
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Returnbook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField f1;
    private javax.swing.JTextField f2;
    private javax.swing.JTextField f3;
    private javax.swing.JTextField f4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
